spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        generate_statistics: true
        show_sql: true
        format_sql: true
        use_sql: true
        new_generator_mappings: false
        autoregister_listeners: false
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/article_bucket?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
